name: 'HCL AppScan CodeSweep'
description: 'Scan for security issues in code'
branding:
  color: 'blue'
  icon: 'lock'  
inputs:
  asoc_key:
    description: 'API key for connecting to ASoC.'
    required: true
  asoc_secret:
    description: 'Secret for connecting to ASoC.'
    required: true
  status:
    description: 'The status of the checks if any security issues are found. One of action_required, failure, or neutral.'
    required: false
    default: 'neutral'
runs:
  using: 'docker'
  image: 'docker://hclcr.io/appscan/codesweep-action:latest'
